//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComiteeMeeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComiteeMeeting()
        {
            this.Fyp2MeetingMapping = new HashSet<Fyp2MeetingMapping>();
            this.GroupSchedules = new HashSet<GroupSchedule>();
            this.Fyp1StudentEvaluationMarks = new HashSet<Fyp1StudentEvaluationMarks>();
            this.MeetingParameterMappings = new HashSet<MeetingParameterMapping>();
            this.FypStudentEvaluationRemarks = new HashSet<FypStudentEvaluationRemark>();
        }
    
        public int id { get; set; }
        public string meetingDescription { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.TimeSpan> startTime { get; set; }
        public Nullable<System.TimeSpan> endTime { get; set; }
        public string venue { get; set; }
        public string selectedDays { get; set; }
        public Nullable<int> sessionID { get; set; }
        public Nullable<bool> isGraded { get; set; }
        public Nullable<bool> isFileRequired { get; set; }
        public string title { get; set; }
    
        public virtual Session Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2MeetingMapping> Fyp2MeetingMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupSchedule> GroupSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp1StudentEvaluationMarks> Fyp1StudentEvaluationMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingParameterMapping> MeetingParameterMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FypStudentEvaluationRemark> FypStudentEvaluationRemarks { get; set; }
    }
}
