//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enrollment()
        {
            this.Fyp1StudentEvaluationMarks = new HashSet<Fyp1StudentEvaluationMarks>();
            this.Fyp2StudentEvaluationMarks = new HashSet<Fyp2StudentEvaluationMarks>();
            this.Fyp2StudentEvaluationRemarks = new HashSet<Fyp2StudentEvaluationRemarks>();
            this.FypStudentEvaluationRemarks = new HashSet<FypStudentEvaluationRemark>();
        }
    
        public int id { get; set; }
        public string studentID { get; set; }
        public Nullable<int> sessionID { get; set; }
        public string subject { get; set; }
        public string grade { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp1StudentEvaluationMarks> Fyp1StudentEvaluationMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2StudentEvaluationMarks> Fyp2StudentEvaluationMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2StudentEvaluationRemarks> Fyp2StudentEvaluationRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FypStudentEvaluationRemark> FypStudentEvaluationRemarks { get; set; }
    }
}
