//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fyp1ParameterEvaluator
    {
        public int id { get; set; }
        public Nullable<int> parameterID { get; set; }
        public string evaluatorID { get; set; }
    
        public virtual Fyp1EvaluationParameters Fyp1EvaluationParameters { get; set; }
        public virtual User User { get; set; }
    }
}
