//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fyp1StudentEvaluationMarks
    {
        public int id { get; set; }
        public Nullable<int> studentEnrollID { get; set; }
        public int meetingID { get; set; }
        public string evaluatorID { get; set; }
        public int parameterID { get; set; }
        public int subParameterID { get; set; }
        public Nullable<decimal> obtainedMarks { get; set; }
        public Nullable<decimal> maxMarks { get; set; }
        public Nullable<int> sessionID { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual ComiteeMeeting ComiteeMeeting { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual Fyp1EvaluationParameters Fyp1EvaluationParameters { get; set; }
        public virtual Session Session { get; set; }
        public virtual Fyp1SubParameter Fyp1SubParameter { get; set; }
    }
}
