//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fyp1SubParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fyp1SubParameter()
        {
            this.Fyp1StudentEvaluationMarks = new HashSet<Fyp1StudentEvaluationMarks>();
        }
    
        public int id { get; set; }
        public Nullable<int> parameterID { get; set; }
        public string name { get; set; }
        public Nullable<int> percentage { get; set; }
    
        public virtual Fyp1EvaluationParameters Fyp1EvaluationParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp1StudentEvaluationMarks> Fyp1StudentEvaluationMarks { get; set; }
    }
}
