//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fyp1EvaluationParameters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fyp1EvaluationParameters()
        {
            this.Fyp1ParameterEvaluator = new HashSet<Fyp1ParameterEvaluator>();
            this.Fyp1SubParameter = new HashSet<Fyp1SubParameter>();
            this.Fyp1StudentEvaluationMarks = new HashSet<Fyp1StudentEvaluationMarks>();
            this.MeetingParameterMappings = new HashSet<MeetingParameterMapping>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> percentage { get; set; }
        public Nullable<int> sessionID { get; set; }
        public Nullable<bool> allowEvaluation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp1ParameterEvaluator> Fyp1ParameterEvaluator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp1SubParameter> Fyp1SubParameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp1StudentEvaluationMarks> Fyp1StudentEvaluationMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingParameterMapping> MeetingParameterMappings { get; set; }
    }
}
