//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fyp2StudentEvaluationRemarks
    {
        public int id { get; set; }
        public Nullable<int> studentEnrollID { get; set; }
        public Nullable<int> taskID { get; set; }
        public string evaluatorID { get; set; }
        public Nullable<int> sessionID { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
        public virtual Session Session { get; set; }
        public virtual Fyp2Task Fyp2Task { get; set; }
    }
}
