//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fyp2Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fyp2Task()
        {
            this.Fyp2StudentEvaluationMarks = new HashSet<Fyp2StudentEvaluationMarks>();
            this.Fyp2StudentEvaluationRemarks = new HashSet<Fyp2StudentEvaluationRemarks>();
        }
    
        public int id { get; set; }
        public Nullable<int> sessionID { get; set; }
        public string taskTitle { get; set; }
        public Nullable<int> groupId { get; set; }
        public string taskDescription { get; set; }
        public Nullable<System.DateTime> assignedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2StudentEvaluationMarks> Fyp2StudentEvaluationMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2StudentEvaluationRemarks> Fyp2StudentEvaluationRemarks { get; set; }
        public virtual ProjectGroup ProjectGroup { get; set; }
        public virtual Session Session { get; set; }
    }
}
