//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fyp2SubParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fyp2SubParameter()
        {
            this.Fyp2StudentEvaluationMarks = new HashSet<Fyp2StudentEvaluationMarks>();
        }
    
        public int id { get; set; }
        public Nullable<int> parameterID { get; set; }
        public string name { get; set; }
        public Nullable<decimal> percentage { get; set; }
    
        public virtual Fyp2EvaluationParameters Fyp2EvaluationParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2StudentEvaluationMarks> Fyp2StudentEvaluationMarks { get; set; }
    }
}
