//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fyp2MeetingMapping
    {
        public int id { get; set; }
        public Nullable<int> meetingID { get; set; }
        public Nullable<int> parameterID { get; set; }
    
        public virtual ComiteeMeeting ComiteeMeeting { get; set; }
        public virtual Fyp2EvaluationParameters Fyp2EvaluationParameters { get; set; }
    }
}
