//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fyp2EvaluationParameters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fyp2EvaluationParameters()
        {
            this.Fyp2MeetingMapping = new HashSet<Fyp2MeetingMapping>();
            this.Fyp2StudentEvaluationMarks = new HashSet<Fyp2StudentEvaluationMarks>();
            this.Fyp2SubParameter = new HashSet<Fyp2SubParameter>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public Nullable<int> sessionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2MeetingMapping> Fyp2MeetingMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2StudentEvaluationMarks> Fyp2StudentEvaluationMarks { get; set; }
        public virtual Session Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2SubParameter> Fyp2SubParameter { get; set; }
    }
}
