//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FypStudentEvaluationRemark
    {
        public int id { get; set; }
        public int studentEnrollID { get; set; }
        public int meetingID { get; set; }
        public string evaluatorID { get; set; }
        public int sessionID { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    
        public virtual ComiteeMeeting ComiteeMeeting { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual User User { get; set; }
        public virtual Session Session { get; set; }
    }
}
