//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupRequest()
        {
            this.GroupRequestMembers = new HashSet<GroupRequestMember>();
        }
    
        public int RequestID { get; set; }
        public string FromRegNum { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRequestMember> GroupRequestMembers { get; set; }
        public virtual Student Student { get; set; }
        public virtual Session Session { get; set; }
    }
}
