//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupSchedule()
        {
            this.MeetingAttendances = new HashSet<MeetingAttendance>();
            this.MeetingQueues = new HashSet<MeetingQueue>();
        }
    
        public int id { get; set; }
        public Nullable<int> groupID { get; set; }
        public Nullable<int> comiteeMeetingID { get; set; }
        public string filePath { get; set; }
        public string Status { get; set; }
        public Nullable<System.TimeSpan> estimatedTime { get; set; }
        public Nullable<System.DateTime> meetingDate { get; set; }
        public Nullable<int> isAttend { get; set; }
        public string type { get; set; }
        public string studentID { get; set; }
    
        public virtual ComiteeMeeting ComiteeMeeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingAttendance> MeetingAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingQueue> MeetingQueues { get; set; }
    }
}
