//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRequestMember
    {
        public int ID { get; set; }
        public int RequestID { get; set; }
        public string MemberRegNum { get; set; }
        public string Status { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual GroupRequest GroupRequest { get; set; }
    }
}
