//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingAttendance
    {
        public int id { get; set; }
        public Nullable<int> scheduleID { get; set; }
        public Nullable<bool> attendance { get; set; }
        public string remarks { get; set; }
        public string studentID { get; set; }
    
        public virtual GroupSchedule GroupSchedule { get; set; }
    }
}
