//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingQueue()
        {
            this.MeetingQueueAttendances = new HashSet<MeetingQueueAttendance>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> meetingDate { get; set; }
        public Nullable<System.TimeSpan> meetingTime { get; set; }
        public string status { get; set; }
        public Nullable<int> scheduleID { get; set; }
        public Nullable<int> sessionID { get; set; }
    
        public virtual GroupSchedule GroupSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingQueueAttendance> MeetingQueueAttendances { get; set; }
        public virtual Session Session { get; set; }
    }
}
