//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingParameterMapping
    {
        public int id { get; set; }
        public int meetingID { get; set; }
        public int parameterID { get; set; }
    
        public virtual ComiteeMeeting ComiteeMeeting { get; set; }
        public virtual Fyp1EvaluationParameters Fyp1EvaluationParameters { get; set; }
    }
}
