//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingSery
    {
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string DaysOfWeek { get; set; }
        public string Venue { get; set; }
        public Nullable<bool> IsRecurring { get; set; }
    }
}
