//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationRecipient
    {
        public int ID { get; set; }
        public Nullable<int> NotificationID { get; set; }
        public string RecipientID { get; set; }
        public string RecipientRole { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<System.DateTime> ReadAt { get; set; }
    
        public virtual Notification Notification { get; set; }
    }
}
