//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FypProjectProgDBEntities : DbContext
    {
        public FypProjectProgDBEntities()
            : base("name=FypProjectProgDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComiteeMeeting> ComiteeMeetings { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<Fyp1EvaluationParameters> Fyp1EvaluationParameters { get; set; }
        public virtual DbSet<Fyp1ParameterEvaluator> Fyp1ParameterEvaluator { get; set; }
        public virtual DbSet<Fyp1StudentEvaluationMarks> Fyp1StudentEvaluationMarks { get; set; }
        public virtual DbSet<Fyp1SubParameter> Fyp1SubParameter { get; set; }
        public virtual DbSet<Fyp2EvaluationParameters> Fyp2EvaluationParameters { get; set; }
        public virtual DbSet<Fyp2MeetingMapping> Fyp2MeetingMapping { get; set; }
        public virtual DbSet<Fyp2StudentEvaluationMarks> Fyp2StudentEvaluationMarks { get; set; }
        public virtual DbSet<Fyp2StudentEvaluationRemarks> Fyp2StudentEvaluationRemarks { get; set; }
        public virtual DbSet<Fyp2SubParameter> Fyp2SubParameter { get; set; }
        public virtual DbSet<Fyp2Task> Fyp2Task { get; set; }
        public virtual DbSet<FypStudentEvaluationRemark> FypStudentEvaluationRemarks { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<GroupRequestMember> GroupRequestMembers { get; set; }
        public virtual DbSet<GroupRequest> GroupRequests { get; set; }
        public virtual DbSet<GroupSchedule> GroupSchedules { get; set; }
        public virtual DbSet<MeetingAttendance> MeetingAttendances { get; set; }
        public virtual DbSet<MeetingParameterMapping> MeetingParameterMappings { get; set; }
        public virtual DbSet<MeetingQueue> MeetingQueues { get; set; }
        public virtual DbSet<MeetingQueueAttendance> MeetingQueueAttendances { get; set; }
        public virtual DbSet<MeetingSery> MeetingSeries { get; set; }
        public virtual DbSet<NotificationRecipient> NotificationRecipients { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<OfferedProject> OfferedProjects { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectGroup> ProjectGroups { get; set; }
        public virtual DbSet<RecurringMeetingDay> RecurringMeetingDays { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<StudentFypAttempt> StudentFypAttempts { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<SupervisorAttendance> SupervisorAttendances { get; set; }
        public virtual DbSet<SuperVisorMeeting> SuperVisorMeetings { get; set; }
        public virtual DbSet<SupervisorRemark> SupervisorRemarks { get; set; }
        public virtual DbSet<SupNotBroadCast> SupNotBroadCasts { get; set; }
        public virtual DbSet<SupTaskBroadCast> SupTaskBroadCasts { get; set; }
        public virtual DbSet<TaskEvaluation> TaskEvaluations { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Technology> Technologies { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<SemesterAgenda> SemesterAgendas { get; set; }
    }
}
