//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectGroup()
        {
            this.Fyp2Task = new HashSet<Fyp2Task>();
            this.GroupMembers = new HashSet<GroupMember>();
            this.SupervisorRemarks = new HashSet<SupervisorRemark>();
        }
    
        public int id { get; set; }
        public string createdBy { get; set; }
        public string supervisorID { get; set; }
        public Nullable<int> projectID { get; set; }
        public int isFinalized { get; set; }
        public Nullable<int> createdSession { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2Task> Fyp2Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
        public virtual OfferedProject OfferedProject { get; set; }
        public virtual User User { get; set; }
        public virtual Session Session { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupervisorRemark> SupervisorRemarks { get; set; }
    }
}
