//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.ComiteeMeetings = new HashSet<ComiteeMeeting>();
            this.Enrollments = new HashSet<Enrollment>();
            this.Fyp1StudentEvaluationMarks = new HashSet<Fyp1StudentEvaluationMarks>();
            this.Fyp2EvaluationParameters = new HashSet<Fyp2EvaluationParameters>();
            this.Fyp2StudentEvaluationMarks = new HashSet<Fyp2StudentEvaluationMarks>();
            this.Fyp2StudentEvaluationRemarks = new HashSet<Fyp2StudentEvaluationRemarks>();
            this.Fyp2Task = new HashSet<Fyp2Task>();
            this.FypStudentEvaluationRemarks = new HashSet<FypStudentEvaluationRemark>();
            this.GroupRequests = new HashSet<GroupRequest>();
            this.MeetingQueues = new HashSet<MeetingQueue>();
            this.OfferedProjects = new HashSet<OfferedProject>();
            this.ProjectGroups = new HashSet<ProjectGroup>();
            this.StudentFypAttempts = new HashSet<StudentFypAttempt>();
            this.Students = new HashSet<Student>();
            this.SuperVisorMeetings = new HashSet<SuperVisorMeeting>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComiteeMeeting> ComiteeMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp1StudentEvaluationMarks> Fyp1StudentEvaluationMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2EvaluationParameters> Fyp2EvaluationParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2StudentEvaluationMarks> Fyp2StudentEvaluationMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2StudentEvaluationRemarks> Fyp2StudentEvaluationRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fyp2Task> Fyp2Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FypStudentEvaluationRemark> FypStudentEvaluationRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRequest> GroupRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingQueue> MeetingQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferedProject> OfferedProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectGroup> ProjectGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentFypAttempt> StudentFypAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuperVisorMeeting> SuperVisorMeetings { get; set; }
    }
}
