//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFypAttempt
    {
        public int attemptId { get; set; }
        public string studentId { get; set; }
        public Nullable<int> sessionId { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<byte> fypType { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
    }
}
