//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupervisorAttendance
    {
        public int id { get; set; }
        public Nullable<int> memberID { get; set; }
        public Nullable<System.DateTime> attendanceDate { get; set; }
        public Nullable<bool> isAttend { get; set; }
        public Nullable<int> meetingID { get; set; }
    
        public virtual SuperVisorMeeting SuperVisorMeeting { get; set; }
    }
}
