//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupervisorRemark
    {
        public int Id { get; set; }
        public Nullable<int> MeetingID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> StudentEnrollID { get; set; }
        public string SupervisorID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual ProjectGroup ProjectGroup { get; set; }
        public virtual SuperVisorMeeting SuperVisorMeeting { get; set; }
        public virtual User User { get; set; }
    }
}
