//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperVisorMeeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuperVisorMeeting()
        {
            this.RecurringMeetingDays = new HashSet<RecurringMeetingDay>();
            this.SupervisorAttendances = new HashSet<SupervisorAttendance>();
            this.SupervisorRemarks = new HashSet<SupervisorRemark>();
            this.SupNotBroadCasts = new HashSet<SupNotBroadCast>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public string day { get; set; }
        public string venue { get; set; }
        public string createdBy { get; set; }
        public Nullable<int> groupID { get; set; }
        public Nullable<bool> isRecurring { get; set; }
        public string memberId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> pptRequired { get; set; }
        public string filePath { get; set; }
        public Nullable<int> sessionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecurringMeetingDay> RecurringMeetingDays { get; set; }
        public virtual Session Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupervisorAttendance> SupervisorAttendances { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupervisorRemark> SupervisorRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupNotBroadCast> SupNotBroadCasts { get; set; }
    }
}
