//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.SupTaskBroadCasts = new HashSet<SupTaskBroadCast>();
            this.TaskEvaluations = new HashSet<TaskEvaluation>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string taskDescription { get; set; }
        public Nullable<System.DateTime> assignDate { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public string assignedBy { get; set; }
        public Nullable<int> groupID { get; set; }
        public string studentID { get; set; }
        public Nullable<bool> isPptRequired { get; set; }
        public string taskStatus { get; set; }
    
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupTaskBroadCast> SupTaskBroadCasts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskEvaluation> TaskEvaluations { get; set; }
        public virtual User User { get; set; }
    }
}
