//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressMonitoringProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskEvaluation
    {
        public int id { get; set; }
        public Nullable<int> taskID { get; set; }
        public string taskRemarks { get; set; }
        public string submissionFilePath { get; set; }
        public Nullable<System.DateTime> submissionDate { get; set; }
        public string progressStatus { get; set; }
        public Nullable<int> score { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
